### ISSUE TITLE
Maturing to v1.0.0

### ISSUE THREAD

**Issue by leleuj** [pac4j/dropwizard-pac4j#4]
1) I haven't seen any communication about this extension on the Dropwizard mailing list: did you post something? It would be great to get some feedbacks.

2) The current version is 0.0.1-SNAPSHOT: what's the strategy to reach the 1.0.0 version?

3) Shouldn't this extension be hosted in the pac4j organization?

**Comment by evnm** [comment]
1. I haven't posted anything since that initial dropwizard-user@ thread in which we first discussed the library. No one has reached out with commentary, so I haven't received any feedback either.
2. I've considered this library to be in a holding pattern until we see evidence that its functionality is desired by Dropwizard users. Without concrete feedback from folks trying to use it, it seems preemptive to arbitrarily mint a 1.0.0 release. We should release a series of 0.x stable versions that folks can try out before we solidify APIs.
3. Transferring the library to the pac4j org is fine by me. Regardless of which org the project falls under, `dropwizard-pac4j` should be added to [modules.dropwizard.io](http://modules.dropwizard.io/) once a stable version is released.

To be honest, I don't think I'm the right person to maintain `dropwizard-pac4j` long-term, since I don't work on any projects that currently use pac4j. I will of course stick around to consult on the Dropwizard side of things.

**Comment by leleuj** [comment]
1. I think we need something more engaging, like "Secure your Dropwizard services with pac4j", but there is no hurry

2. It feels like the "Egg or chicken" story ;-) I think there is always a need for a good security library to secure web services. So I think our main concern is to make `dropwizard-pac4j` known and used by Dropwizard users so that feedbacks and inquiries come.

3. Noticed for the modules.dropwizard.io

"I don't think I'm the right person to maintain dropwizard-pac4j long-term": I have absolutely no problem with that, this is open source and free involvement. And the "eat your own dog food" is a key rule. In that case, **can you transfer this project to the `pac4j` organization so that we can take over?**

**Comment by evnm** [comment]
Sounds like we're in agreement. I'm happy to transfer the project to the pac4j org. As for getting the word out, how about we wait until a) @victornoel's JAX-RS redux of this library is merged and b) a stable version of `dropwizard-pac4j` is released, at which point we can send mail to dropwizard-user@, pac4j-users@, and any other relevant mailing lists.

**Comment by evnm** [comment]
@leleuj, could you please delete the existing pac4j/dropwizard-pac4j repository? I can't complete transfer until it is removed.

**Comment by leleuj** [comment]
I just deleted the `pac4j/dropwizard-pac4j` repository: it should be ok now.

**Comment by victornoel** [comment]
On my side, I am using all these libraries in an application that is under development in my company. In the coming month I will be playing more and more with the advanced features of pac4j (to have SSO, for now I only use a simple login with users in a local database).
It's currently not accessible, because we are reworking our forge/CI infrastructure, but it's under an AGPL license, so it will be visible also in the month I guess... 

I think we can at least release 0.x versions quite quickly and wait for a 1.0.0 until I have (or someone else) used the more advanced features that makes pac4j a relevant architectural choice :)
We can still advertise the 0.x version I think :)

There is a good chance that things may need to be changed in a breaking way I think, both in jac-rs-pac4j and dropwizard-pac4j.

**Comment by leleuj** [comment]
Great to have you as an intensive user and contributor!

We must not fear breaking changes. If so, we'll upgrade to version 2.0.0.

**Comment by evnm** [comment]
Ugh, so apparently in order to transfer a repo, the person making the transfer has to have admin/owner rights to the recipient account/organization: https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/

**Comment by victornoel** [comment]
@evnm the other solution would maybe to transfer it to @leleuj and let him put it in the organisation.

Also Ithink this [page](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) is more likely to apply to your case @evnm since the repository is in your private account :)

**Comment by leleuj** [comment]
Everything is ok now. I moved it to the `pac4j` organization.

**Comment by victornoel** [comment]
@leleuj great :) any ETA for deployment on Sonatype snapshot repository?

**Comment by leleuj** [comment]
I just did it. In fact, the build fails due to the `EndToEnd` class tests and I noticed that the README is out-of-date as well (it mentioned the `j2e-pac4j` library instead of the `jax-rs-pac4j` one). But you should be able to fix that easily.

**Comment by victornoel** [comment]
@leleuj should be alright with #7, thanks!

**Comment by leleuj** [comment]
Build is ok, but deployment fails. Checking...

**Comment by leleuj** [comment]
It's good now: https://oss.sonatype.org/content/repositories/snapshots/org/pac4j/dropwizard-pac4j/0.0.1-SNAPSHOT/

**Comment by victornoel** [comment]
@leleuj maybe it would make sense that until 1.0.0, I get push rights on this repository and maybe also jax-rs-pac4j? I will still make PR for everything concerning pac4j itself so that you can review :)

**Comment by leleuj** [comment]
Lets' do that for now. You should have received invitations...

**Comment by victornoel** [comment]
Thanks!

**Comment by leleuj** [comment]
As I just released version 1.0.0, we can close this issue.

**Comment by victornoel** [comment]
Thanks @leleuj :)

FYI @evnm I will announce it soon on dropwizard mailing list :)
